arrowParens: 'avoid'
bracketSpacing: false
endOfLine: 'lf'
printWidth: 120
quoteProps: 'consistent'
singleQuote: true
trailingComma: 'es5'

plugins: ['prettier-plugin-tailwindcss']

# prettier-plugin-tailwindcss
tailwindFunctions: ['twMerge']
